export const SCHEMA_STATEMENTS = [
  `CREATE TABLE IF NOT EXISTS form (
    id      TEXT PRIMARY KEY,
    code    TEXT UNIQUE,
    type    TEXT NOT NULL,
    scope   TEXT NOT NULL,
    owner   TEXT,
    title   TEXT,
    public  INTEGER DEFAULT 0,
    active  INTEGER DEFAULT 1,
    data    TEXT,
    time    TEXT DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS matter (
    id       TEXT PRIMARY KEY,
    form     TEXT,
    title    TEXT NOT NULL,
    type     TEXT,
    qty      REAL DEFAULT 0,
    unit     TEXT,
    value    REAL DEFAULT 0,
    data     TEXT,
    scope    TEXT,
    active   INTEGER DEFAULT 1,
    start    TEXT,
    end      TEXT,
    life     INTEGER,
    owner    TEXT,
    time     TEXT DEFAULT CURRENT_TIMESTAMP,
    updated  TEXT
  )`,
  `CREATE TABLE IF NOT EXISTS motion (
    stream     TEXT NOT NULL,
    seq        INTEGER NOT NULL,
    action     INTEGER NOT NULL,
    phase      INTEGER,
    delta      REAL,
    client_ref TEXT,
    data       TEXT,
    time       TEXT DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (stream, seq)
  )`,
  `CREATE TABLE IF NOT EXISTS graph (
    src    TEXT NOT NULL,
    rel    TEXT NOT NULL,
    tgt    TEXT NOT NULL,
    active INTEGER DEFAULT 1,
    data   TEXT,
    time   TEXT DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (src, rel, tgt)
  )`,
  `CREATE TABLE IF NOT EXISTS memory (
    id        TEXT NOT NULL,
    chunk     INTEGER NOT NULL DEFAULT 0,
    matter    TEXT,
    text      TEXT,
    embedding BLOB,
    meta      TEXT,
    PRIMARY KEY (id, chunk)
  )`,
  `CREATE INDEX IF NOT EXISTS matter_scope_type ON matter(scope, type, active, time)`,
  `CREATE INDEX IF NOT EXISTS matter_owner ON matter(scope, owner, active)`,
  `CREATE INDEX IF NOT EXISTS form_scope_type ON form(scope, type, active)`,
  `CREATE INDEX IF NOT EXISTS motion_stream ON motion(stream, seq)`,
  `CREATE INDEX IF NOT EXISTS graph_tgt ON graph(tgt, rel, src)`,
  `CREATE INDEX IF NOT EXISTS idx_memory_matter ON memory(matter)`,
];
