import React, { useState, useEffect } from "react";
import {
  StyleSheet,
  View,
  Text,
  TouchableOpacity,
  TextInput,
  KeyboardAvoidingView,
  Platform,
  Alert,
  ScrollView
} from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { Stack, useRouter } from "expo-router";
import { Ionicons } from "@expo/vector-icons";
import { StatusBar } from "expo-status-bar";
import { getDbClient } from "../lib/db";

const genMotionId = () => `mot_${Date.now()}_${Math.random().toString(36).substring(2, 8)}`;
const genStreamId = () => `str_${Date.now()}_${Math.random().toString(36).substring(2, 6)}`;

type ActionType = "sale" | "inventory" | "reminder" | "task" | "custom";

export default function MotionScreen() {
  const router = useRouter();
  
  // High-level UX states
  const [selectedType, setSelectedType] = useState<ActionType>("task");
  const [message, setMessage] = useState("");
  const [amountOrDelta, setAmountOrDelta] = useState("");
  const [scope, setScope] = useState("");
  const [status, setStatus] = useState<"PENDING" | "COMPLETED">("PENDING");

  // Advanced low-level database states (autogenerated but editable)
  const [showAdvanced, setShowAdvanced] = useState(false);
  const [motionId, setMotionId] = useState(genMotionId());
  const [streamId, setStreamId] = useState(genStreamId());
  const [seq, setSeq] = useState("1");
  const [customAction, setCustomAction] = useState("151");
  const [customData, setCustomData] = useState("");
  
  const [isSaving, setIsSaving] = useState(false);

  // Set default status and advanced codes when selected type changes
  useEffect(() => {
    switch (selectedType) {
      case "sale":
        setStatus("COMPLETED");
        setCustomAction("1");
        break;
      case "inventory":
        setStatus("COMPLETED");
        setCustomAction("51");
        break;
      case "reminder":
        setStatus("PENDING");
        setCustomAction("101");
        break;
      case "task":
        setStatus("PENDING");
        setCustomAction("151");
        break;
      case "custom":
        setStatus("COMPLETED");
        break;
    }
  }, [selectedType]);

  const handleSave = async () => {
    if (!message.trim() && selectedType !== "custom") {
      Alert.alert("Validation Error", "Please enter a message or title for this log.");
      return;
    }

    if (isSaving) return;
    setIsSaving(true);

    console.log("[Motion:Save] Start saving motion log", {
      motionId,
      streamId,
      seq,
      selectedType,
      customAction,
      amountOrDelta,
      status,
      scope
    });

    try {
      const db = getDbClient();
      const time = new Date().toISOString();

      // Determine numeric action code
      let finalAction = parseInt(customAction, 10);
      if (isNaN(finalAction)) finalAction = 100;

      // Determine numeric delta
      const parsedDelta = amountOrDelta ? parseFloat(amountOrDelta) : null;

      // Structure data JSON string based on high-level UX inputs
      let finalDataStr = "";
      if (selectedType === "custom") {
        finalDataStr = customData.trim() || "{}";
      } else {
        const dataObj: Record<string, any> = {};
        if (selectedType === "task" || selectedType === "reminder") {
          dataObj.task = message.trim();
        } else {
          dataObj.title = message.trim();
        }
        
        if (parsedDelta !== null) {
          dataObj.qty = parsedDelta;
        }
        finalDataStr = JSON.stringify(dataObj);
      }

      console.log("[Motion:Save] Writing to database...", {
        motionId,
        streamId,
        finalAction,
        status,
        parsedDelta,
        finalDataStr,
        time
      });

      await db.run(
        `INSERT INTO motion (id, stream, seq, action, status, delta, scope, data, time) 
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`,
        [
          motionId,
          streamId,
          parseInt(seq, 10) || 1,
          finalAction,
          status,
          parsedDelta,
          scope.trim() || null,
          finalDataStr,
          time
        ]
      );

      console.log("[Motion:Save] Database write complete. Motion record successfully saved.");

      router.back();

      // No-op sync in local mode
    } catch (error: any) {
      console.error("[Motion:Save] Failed to create motion:", error);
      Alert.alert("Error", error?.message || "Failed to create motion log.");
      setIsSaving(false);
    }
  };

  const actionTypes: { type: ActionType; label: string; icon: string }[] = [
    { type: "task", label: "Task", icon: "checkbox" },
    { type: "reminder", label: "Reminder", icon: "notifications" },
    { type: "sale", label: "Sale", icon: "receipt" },
    { type: "inventory", label: "Inventory", icon: "cube" },
    { type: "custom", label: "Custom", icon: "options" },
  ];

  return (
    <SafeAreaView style={styles.container}>
      <StatusBar style="dark" />
      <Stack.Screen options={{ presentation: "modal", headerShown: false }} />

      <View style={styles.header}>
        <Text style={styles.headerTitle}>Create Motion Log</Text>
        <TouchableOpacity onPress={() => router.back()} style={styles.closeBtn}>
          <Ionicons name="close" size={24} color="#333" />
        </TouchableOpacity>
      </View>

      <KeyboardAvoidingView
        behavior={Platform.OS === "ios" ? "padding" : undefined}
        style={styles.keyboardView}
      >
        <ScrollView style={styles.content} keyboardShouldPersistTaps="handled">
          
          {/* Action Type Selector */}
          <Text style={styles.label}>Log Category</Text>
          <View style={styles.chipContainer}>
            {actionTypes.map(item => {
              const isSelected = selectedType === item.type;
              return (
                <TouchableOpacity
                  key={item.type}
                  style={[styles.chip, isSelected && styles.chipSelected]}
                  onPress={() => setSelectedType(item.type)}
                >
                  <Ionicons
                    name={item.icon as any}
                    size={16}
                    color={isSelected ? "#ffffff" : "#64748b"}
                    style={{ marginRight: 6 }}
                  />
                  <Text style={[styles.chipText, isSelected && styles.chipTextSelected]}>
                    {item.label}
                  </Text>
                </TouchableOpacity>
              );
            })}
          </View>

          {/* Dynamic input depending on selected type */}
          {selectedType !== "custom" && (
            <>
              <Text style={styles.label}>
                {selectedType === "task" && "Task Description"}
                {selectedType === "reminder" && "Reminder Text"}
                {selectedType === "sale" && "Product / Service Sold"}
                {selectedType === "inventory" && "Inventory Description / Product Title"}
              </Text>
              <TextInput
                style={styles.input}
                placeholder={
                  selectedType === "task" ? "e.g. Call client for feedback" :
                  selectedType === "reminder" ? "e.g. System upgrade at midnight" :
                  selectedType === "sale" ? "e.g. Dark Chocolate Swirl" :
                  "e.g. Raw cocoa powder packs"
                }
                placeholderTextColor="#94a3b8"
                value={message}
                onChangeText={setMessage}
              />
            </>
          )}

          {/* Amount / Delta field for Sale / Inventory */}
          {(selectedType === "sale" || selectedType === "inventory") && (
            <>
              <Text style={styles.label}>
                {selectedType === "sale" ? "Sale Price / Value (₹)" : "Quantity Delta (e.g. +10 or -5)"}
              </Text>
              <TextInput
                style={styles.input}
                placeholder="0.0"
                placeholderTextColor="#94a3b8"
                keyboardType="numeric"
                value={amountOrDelta}
                onChangeText={setAmountOrDelta}
              />
            </>
          )}

          {/* Status Toggle */}
          <Text style={styles.label}>Initial Status</Text>
          <View style={styles.statusToggleContainer}>
            <TouchableOpacity
              style={[styles.statusToggleBtn, status === "PENDING" && styles.statusToggleBtnSelected]}
              onPress={() => setStatus("PENDING")}
            >
              <Text style={[styles.statusToggleText, status === "PENDING" && styles.statusToggleTextSelected]}>
                Pending
              </Text>
            </TouchableOpacity>
            <TouchableOpacity
              style={[styles.statusToggleBtn, status === "COMPLETED" && styles.statusToggleBtnSelected]}
              onPress={() => setStatus("COMPLETED")}
            >
              <Text style={[styles.statusToggleText, status === "COMPLETED" && styles.statusToggleTextSelected]}>
                Completed
              </Text>
            </TouchableOpacity>
          </View>

          {/* Scope input */}
          <Text style={styles.label}>Scope (Optional context tag)</Text>
          <TextInput
            style={styles.input}
            placeholder="e.g. store_1, shift_morning"
            placeholderTextColor="#94a3b8"
            value={scope}
            onChangeText={setScope}
          />

          {/* Collapsible Advanced Section */}
          <TouchableOpacity
            style={styles.advancedHeader}
            onPress={() => setShowAdvanced(prev => !prev)}
          >
            <Text style={styles.advancedHeaderText}>Advanced Database Parameters</Text>
            <Ionicons
              name={showAdvanced ? "chevron-up" : "chevron-down"}
              size={18}
              color="#64748b"
            />
          </TouchableOpacity>

          {showAdvanced && (
            <View style={styles.advancedPanel}>
              <Text style={styles.label}>Motion ID</Text>
              <TextInput
                style={styles.advancedInput}
                value={motionId}
                onChangeText={setMotionId}
              />

              <Text style={styles.label}>Stream ID</Text>
              <TextInput
                style={styles.advancedInput}
                value={streamId}
                onChangeText={setStreamId}
              />

              <View style={{ flexDirection: "row", gap: 12 }}>
                <View style={{ flex: 1 }}>
                  <Text style={styles.label}>Sequence (Seq)</Text>
                  <TextInput
                    style={styles.advancedInput}
                    keyboardType="numeric"
                    value={seq}
                    onChangeText={setSeq}
                  />
                </View>
                <View style={{ flex: 1 }}>
                  <Text style={styles.label}>Action Opcode</Text>
                  <TextInput
                    style={styles.advancedInput}
                    keyboardType="numeric"
                    value={customAction}
                    onChangeText={setCustomAction}
                  />
                </View>
              </View>

              {selectedType === "custom" && (
                <>
                  <Text style={styles.label}>Raw JSON Data Block</Text>
                  <TextInput
                    style={[styles.advancedInput, styles.textArea]}
                    placeholder="{}"
                    placeholderTextColor="#94a3b8"
                    value={customData}
                    onChangeText={setCustomData}
                    multiline
                  />
                </>
              )}
            </View>
          )}

          {/* Submit Button */}
          <TouchableOpacity
            style={[styles.saveBtn, isSaving && styles.saveBtnDisabled]}
            onPress={handleSave}
            disabled={isSaving}
          >
            <Text style={styles.saveBtnText}>
              {isSaving ? "Saving Log..." : "Log Motion"}
            </Text>
          </TouchableOpacity>

          <View style={{ height: 40 }} />
        </ScrollView>
      </KeyboardAvoidingView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 15,
    borderBottomWidth: 1,
    borderBottomColor: "#f1f5f9",
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#0f172a",
  },
  closeBtn: {
    padding: 10,
    marginRight: -10,
  },
  keyboardView: {
    flex: 1,
  },
  content: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 10,
  },
  label: {
    fontSize: 12,
    fontWeight: "600",
    color: "#64748b",
    marginBottom: 6,
    marginTop: 14,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  input: {
    borderWidth: 1,
    borderColor: "#e2e8f0",
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 10,
    fontSize: 15,
    color: "#1e293b",
    backgroundColor: "#f8fafc",
  },
  chipContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 6,
  },
  chip: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#f1f5f9",
    borderWidth: 1,
    borderColor: "#e2e8f0",
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  chipSelected: {
    backgroundColor: "#1e293b",
    borderColor: "#1e293b",
  },
  chipText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#475569",
  },
  chipTextSelected: {
    color: "#ffffff",
  },
  statusToggleContainer: {
    flexDirection: "row",
    borderWidth: 1,
    borderColor: "#e2e8f0",
    borderRadius: 10,
    overflow: "hidden",
  },
  statusToggleBtn: {
    flex: 1,
    alignItems: "center",
    paddingVertical: 10,
    backgroundColor: "#f8fafc",
  },
  statusToggleBtnSelected: {
    backgroundColor: "#6366f1",
  },
  statusToggleText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#475569",
  },
  statusToggleTextSelected: {
    color: "#ffffff",
  },
  advancedHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 24,
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: "#f1f5f9",
  },
  advancedHeaderText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#475569",
  },
  advancedPanel: {
    backgroundColor: "#f8fafc",
    borderWidth: 1,
    borderColor: "#e2e8f0",
    borderRadius: 10,
    padding: 14,
    marginTop: 8,
  },
  advancedInput: {
    borderWidth: 1,
    borderColor: "#cbd5e1",
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    fontSize: 14,
    color: "#475569",
    backgroundColor: "#ffffff",
    marginBottom: 4,
  },
  textArea: {
    height: 80,
    textAlignVertical: "top",
  },
  saveBtn: {
    backgroundColor: "#1e293b",
    borderRadius: 10,
    paddingVertical: 14,
    alignItems: "center",
    marginTop: 28,
  },
  saveBtnText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600",
  },
  saveBtnDisabled: {
    backgroundColor: "#94a3b8",
  }
});
