name = "s3storage"
main = "src/index.ts"
compatibility_date = "2024-04-03"

[vars]
AWS_ACCESS_KEY_ID = "tid_oYWulzjfLo_yGGspVeMilsGZSBSxQPKAuJzMEIcjKbrYphHkdR"
AWS_SECRET_ACCESS_KEY = "tsec_Fgkpi92OX_Ru2I9Z1RL8vWNRh2z_to3QNkuwhW5vMp5wjCCU95UNzCBkdkkSBggkhEwFig"
AWS_DEFAULT_REGION = "auto"
RAILWAY_STORAGE_ENDPOINT = "https://t3.storageapi.dev"
RAILWAY_STORAGE_BUCKET_NAME = "durable-wardrobe-8osafzz8"
TURSO_URL = "libsql://global-tarframework.aws-eu-west-1.turso.io"
TURSO_AUTH_TOKEN = "eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJhIjoicnciLCJpYXQiOjE3Nzk3ODg4MzcsImlkIjoiMDE5ZTYzYWUtNWIwMS03ZGU2LWI5Y2UtYmRhNDViMzE0ZWY5IiwicmlkIjoiZmYxMzI2OGEtYzAwMy00OGY2LTg4MTItMjBkNGIyNzJjMTc4In0.psIsvB51C4HKwdwTNOEICDiFo2nAREWRscIqlt8BaPxSPb8nKxmTCY3938PeUa273PWORT1UBMBPmhxn3UdYAQ"
TURSO_PLATFORM_API_TOKEN = "eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJWU1hQV0ZqcEVmRzdIQWEyeGhNenZRIiwib3JnX2lkIjoyNjYxOX0.DABRCjTfvm_at_jJXHxMhiib57bZ2SEniJPlbbVil3M79PCNqOVOsxpIvZBaqSe3W-TQYsuny3IvnlxCM0BWAQ"
TURSO_ORG = "tarframework"
TURSO_GROUP = "default"

[ai]
binding = "AI"
