name = "taragent-categorizer"
main = "dist/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
# GROQ_API_KEY will be set as secret via: wrangler secret put GROQ_API_KEY
